package com.concrete.concretenosofa.utils

const val CLEAR_SKY_DAY_01D = "01d"
const val CLEAR_SKY_NIGHT_01N = "01n"
const val FEW_CLOUDS_DAY_02D = "02d"
const val FEW_CLOUDS_NIGHT_02N = "02n"
const val SCATTERED_CLOUDS_DAY_3D = "03d"
const val SCATTERED_CLOUDS_NIGHT_3N = "03n"
const val BROKEN_CLOUDS_DAY_4D = "04d"
const val BROKEN_CLOUDS_NIGHT_4N = "04n"
const val SHOWER_RAIN_DAY_9D = "09d"
const val SHOWER_RAIN_NIGHT_9N = "09n"
const val RAIN_DAY_10D = "10d"
const val RAIN_NIGHT_10N = "10n"
const val THUNDERSTORM_DAY_11D = "11d"
const val THUNDERSTORM_NIGHT_11N = "11n"
